name: CI/CD - Training Dozie Website
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Replace with the desired .NET 8 version
         
      - name: Restore Dependencies
        run: dotnet restore myWebApp.sln
        working-directory: ${{ github.workspace }}
             
      - name: Build Project
        run: dotnet build

      #- name: Publish Project
        #run: dotnet run
