name: CI/CD - Training Dozie Website
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Replace with the desired .NET 8 version
         
      - name: Restore Dependencies
        run: dotnet restore myWebApp.sln
        working-directory: ${{ github.workspace }}
             
      - name: Build Project
        run: dotnet build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app-t
          path: ${{ github.workspace }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app-t
          path: ${{ github.workspace }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.APP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}
